name: lint

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  ruff:
    name: Ruff Check & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruff
        uses: astral-sh/ruff-action@v4.1.0
        with:
          version-file: "requirements.txt"
          args: "--version"

      - name: Ruff check
        id: ruff_check
        run: ruff check --output-format=github

      - name: Ruff format
        run: ruff format --check
        if: always() && steps.ruff_check.outcome != 'skipped'
