name: lint

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  ruff:
    name: Ruff Check & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruff
        uses: astral-sh/setup-ruff@v3
        with:
          version: 0.15.19
          enable-cache: true

      - name: Ruff check
        id: ruff_check
        run: ruff check --output-format=github

      - name: Ruff format
        run: ruff format --check
        if: always() && steps.ruff_check.outcome != 'skipped'
